# SwiftLint Configuration
# Swift 코드 스타일 가이드에 기반한 종합적인 설정
# 참고: Apple, Google, Airbnb, Kodeco, StyleShare Swift Style Guides

# 제외할 디렉토리
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - vendor
  - fastlane

# 비활성화할 규칙
disabled_rules:
  - todo  # TODO 주석 허용
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment

# 애널라이저 규칙 (실행 시간이 길지만 더 깊은 분석)
analyzer_rules:
  - unused_import
  - unused_declaration

# 추가로 활성화할 opt-in 규칙
opt_in_rules:
  # 배열 및 컬렉션
  - array_init
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - last_where
  - collection_alignment

  # 클로저 및 함수
  - closure_end_indentation
  - closure_spacing
  - trailing_closure
  - unneeded_parentheses_in_closure_argument

  # 코드 품질
  - convenience_type
  - discouraged_object_literal
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unused_optional_binding
  - yoda_condition

  # 네이밍
  - prefer_self_type_over_type_of_self

  # 포매팅
  - attributes
  - indentation_width
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

  # 기타
  - pattern_matching_keywords
  - strict_fileprivate
  - legacy_random

# 커스텀 규칙
custom_rules:
  # print 문 사용 금지 (프로덕션 코드)
  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: '(\bprint|\bdebugPrint|\bdump|Swift\.print|Swift\.debugPrint|Swift\.dump)(\s*\()'
    match_kinds:
      - identifier
    message: "print() 대신 적절한 로깅 시스템을 사용하세요. 디버그 전용인 경우 // swiftlint:disable:next no_direct_standard_out_logs를 사용하세요."
    severity: warning

  # @objcMembers 사용 금지
  no_objcMembers:
    name: "@objcMembers is discouraged"
    regex: "@objcMembers"
    message: "각 멤버에 명시적으로 @objc를 사용하세요"
    severity: error

  # #file 대신 #fileID 사용
  no_file_literal:
    name: "#file is disallowed"
    regex: '(\b#file\b)'
    match_kinds:
      - identifier
    message: "#file 대신 #fileID를 사용하세요"
    severity: warning

  # 배열/딕셔너리 초기화 시 명시적 타입 어노테이션 권장
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "빈 배열이나 딕셔너리를 초기화할 때 명시적 타입 어노테이션을 사용하세요"
    severity: warning

# 속성 설정
attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

# 강제 캐스팅 경고
force_cast: warning
force_try: warning

# 함수 본문 길이
function_body_length:
  warning: 50
  error: 100

# 파일 길이
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# 타입 본문 길이
type_body_length:
  warning: 300
  error: 500

# 함수 파라미터 개수
function_parameter_count:
  warning: 5
  error: 8

# 식별자 이름 규칙
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - i
    - j
    - k
    - id
    - x
    - y
    - z
    - r
    - g
    - b
    - a
  validates_start_with_lowercase: true

# 들여쓰기 너비 (2 spaces)
indentation_width:
  indentation_width: 2

# 줄 길이
line_length:
  warning: 100
  error: 120
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# 네스팅 깊이
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# 타입 이름 규칙
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  validates_start_with_lowercase: false

# 여러 줄 인자 정렬
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

# private over fileprivate 강제
private_over_fileprivate:
  validate_extensions: true

# 후행 공백
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

# 수직 공백
vertical_whitespace:
  max_empty_lines: 1

# 클로저 파라미터 위치
closure_parameter_position:
  severity: warning

# Cyclomatic Complexity (순환 복잡도)
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# 리포터 (출력 형식)
reporter: "xcode"
